name = "qr-shortener-worker"
main = "src/worker.ts"
compatibility_date = "2025-11-24"
compatibility_flags = ["nodejs_compat"]

# Specify which Cloudflare account to use (required when you have multiple accounts)
account_id = "568051052fcb248c756d306dece6cfb7"

[vars]
API_BASE_URL = "https://qr-shortener-api.ularkimsanov7.workers.dev"

# Secrets (set via wrangler secret put):
# REDIS_URL=https://xxx.upstash.io
# REDIS_TOKEN=xxx

[env.dev]
vars = { API_BASE_URL = "http://localhost:3001" }
