name = "qr-shortener-worker"
main = "src/worker.ts"
compatibility_date = "2024-11-20"
compatibility_flags = ["nodejs_compat"]

[vars]
# API_BASE_URL = "https://api.example.com"

[env.dev]
vars = { API_BASE_URL = "http://localhost:3001" }
